name: Despliegue a Surge.sh

on:
  push: 
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar Surge
        run: npm install --global surge
      - name: Desplegar a Surge
        run: surge --project ./ --domain ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_API_KEY }}
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}